### ISSUE TITLE
Translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by vpfreitas** [wbnns/bitcoinwhitepaper#18]
I may be interested on translating Satoshi Nakamoto's original paper to Brazilian Portuguese...

Are there any other instructions besides 

"Pull requests with translated versions of this whitepaper are welcome.

Please add a link to the original English version (bitcoin.org/bitcoin.pdf) at the top of the document."

?

**Comment by hteixe** [comment]
Hi vpfreitas.

Ok. Great. That's it for now?

**Comment by gcunhase** [comment]
I'd also like to contribute with @vpfreitas on translate the Bitcoin paper to Brazilian Portuguese, but I've also seen that there's an open pull on this language. Should I request a new pull?

**Comment by dvieirapetrobras** [comment]
I also would like to translate the paper to Brazilian Portuguese. I've been translating more than 160.000 pages on computer science. Please let me know how to do it.

**Comment by camilaavilarinho** [comment]
Any news about the translation? I'd like to help too
@vpfreitas @gcunhase @dvieirapetrobras

**Comment by kcobidus** [comment]
just do it

**Comment by emerqui** [comment]
Is there a translation into Brazilian Portuguese out there?

**Comment by 48KDova** [comment]
Well, I think it should be a Portuguese person to translate that...it's a very different thing

**Comment by 48KDova** [comment]
Just because the Brazilians have have a lot of words in their "Portuguese" language that just don't exist in the real Portuguese dictionary, most of the times they don't even understand us Portuguese and the other way around...or do both...because their are a lot of ppl, I understand the need since only about 7% of their population its capable of a good english understanding, based on the complains of them in that subject

**Comment by dvieirapetrobras** [comment]
Hi there.
I think you must, first of all, try to write English correctly. Your text was carelessly written, and barely deserves any consideration, as far as I'm concerned.
Best regards.
Daniel Vieira

MULTINET Produtos e Serviços de Informática Ltda.



    Em sábado, 13 de janeiro de 2018 11:41:01 BRST, 48KDova <notifications@github.com> escreveu:  
 
 
Just because the Brazilians have have a lot of words in their "Portuguese" language that just don't exist in the real Portuguese dictionary, most of the times they don't even understand us Portuguese and the other way around...or do both...because their are a lot of ppl, I understand the need since only about 7% of their population its capable of a good english understanding, based on the complains of them in that subject

**Comment by 48KDova** [comment]
Yes I can see you´r Brazilien...well I´m writing in a kind of a slang way cause I was not even applyng to wright shit for you, that´s way you guys are so despised here in Portugal, cause of the 210 million ppl you have there, 10% have a brain and character by the way and can´t even take a hint without becaming all touchy, in fact the good ones I know happens to be geniuses but unfortunatly they cannot compensate for the other 180 million dwelling most in the most dangerous streets in the world, and now you gonna hear this, here we are sick of
Tired of configuring our devices in English because when we open a website is always in brazilian but everything ok were not by idiot reviews and the complaints that everything comes in English (see play store reviews) "que tem que doblar, cara, senão a gente não entende" and worst of all is that your comments on applications or software or whatever are completely useless because they are always the same...complaints, and good programs have poor quote due to ignorance.

 

 

P.S- Is this now well written? Because this email address has no corretcor checker, so I had to ask to my primary teacher to write it for me.

Oh and by the way...I love the way you guys talk english...It´s evolutionary

**Comment by 48KDova** [comment]
Oh and pardon me...is "spell corrector", I do not want to offend our top language translator here, considering I´m an ignorant next to you, I´m very sorry for that

**Comment by dvieirapetrobras** [comment]
Excuses accepted.

Daniel Vieira


    Em sábado, 13 de janeiro de 2018 17:34:59 BRST, 48KDova <notifications@github.com> escreveu:  
 
 
Oh and pardon me...is "spell corrector", I do not want to offend our top language translator here, considering I´m an ignorant next to you, I´m very sorry for that

**Comment by 48KDova** [comment]
Thaank you very much
